feign:
  client:
    config:
      default:
        readTimeout: 1500
        connectTimeout: 500
openExchange:
  service:
    base:
      url: https://openexchangerates.org
    name: openExchange
    currency: ${OPEN_EXCHANGE_CURRENCY:USD}
    key: ${OPEN_EXCHANGE_KEY:60b9861d64c44caaa7ed56c2d40f36ad}
giphy:
  service:
    base:
      url: https://api.giphy.com
    name: giphyAPI
    key: ${GIPHY_API_KEY:C7uWSuhiWE4j7Kn3BzetqSMw3tSK5OkW}